language: node_js
node_js:
- '10'
before_script:
- npm run test
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: atsquad@cimpress.com
  api_key:
    secure: ibFoYi1G6Sc/oy7XY8uodp6lQ8tK7EZJnjWudjdJcDFFhavL3j06R1wzTGYlez8rtEieLONQRX1STgNNwJksYzYb02MPdzppjrxN4svRZMn1qQ6Kafly7POhOyTY7MuHpdJylMRIOENRPwI2LF2cabftNQW/XiiK9ryA1T6ROaaTba4OaEjLxRt9xvaHpqDPmsiTqgNY51d6C+nVmFZxgxWKdOpVVu/nky+xQLYruuQscfRPMJKHRKWOwvrGoqfqdenssc7BKGLibHVDlOSjkMptSyf67CJVnfwQ6Gn/YAmPItAUfOxZ/W/nGFjSLT5buf+8dibr5fJI6WpForSdPwo80hBS85BV1y/9yDkJkgMQPRBeyVZerOoB2P2FTBXs4LCz/pYb/+bli1DyrpB+0BtQyFgDggDuIHmerx8YsRKeSA4UPp15ceL4UiOQgJUoEcTFOM303XIAKlRHgmzZe8g0/+V5tpIoEiEZFaDSMXMY9BESpWayGxeiDeRiqb+WlYzZF6EgfAUCzfJfR915tGWsneSh3Ng3leJYp9XJmjm/R+ISyJE86uhy1KNB10VPwYgYNSIQcVrJ44gN00dBSR46C7DFOZaw/FhVcKbpWqrh0He/AzIV+OP2Qbzz0YvDluz1rGX6ir6BYH3nuox+8WqDxJKwIRRv+aRDc3kPPFU=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
    secure: DkRsfbDi3ETQ5ifQi4LxBPD43WEmtBToBurzQsQmAac56gfwLOFS6+5nUG4bQObSbuCzHqclzQwcr6Vd4Q22IYLRh8ue0aFjaa9gXPyoqUPrF6J9utugOxQ6yhm2fHqgtnogekj7sRh3OCyMrK8VrxyYl9qHnA6Q+OCoXD+kmxNlI3eG1gTERY57qq38rCUElA8GYoG6bbzgJpLRfU/vSJLdn0MHrI7Rp9edGoY3uXK5Kw71bR1DfgiIeA4qu9OESHaAKj07/GWtyYO0750LiQZwo+d1t6coyTgjIEmMZ9eiy2NTJPJb7/zk8tEVvgAyox33vyRuOyclkKyZ7VkTxemaFx5tZnhZlwTnrQXSgrCv/WwOkbhSavXQJu6s+YfwvfE8kjbyyCOcWTPdul/6IjVxqJUAhdDc2okXbXcg19JktNGvCwU3fTNI5ee+iijLZVewPSMEI8JoJv4b52oMkxeFWvKs6nXgeKWIpEdgleMs7TYYOj90qIA6QG42M9kbGaPQoklMSp+5E31swdtiAER8pm/N+9s1NkmjkNeNIuOhNACX+RoQbQ2vfOOnVKpw5t3DSHATJbEfhrgDxH166MhNEMI15snT35lfpYgdItZyC7c+F9Cooj48NjQFYmu6eBGxzlvrfCIO4KkmnZ8H2hWMNAIecl2e87cs1xiYwOI=
